### ISSUE TITLE
How to change myself dataset？

### ISSUE THREAD

**Issue by Faker0715** [lgalke/text-clf-baselines#1]
How to change myself dataset？

**Comment by lgalke** [comment]
Either prepare your own dataset in the same format as here https://github.com/lgalke/text_gcn/tree/master/data
or write your own data loading pipeline https://github.com/lgalke/text-clf-baselines/blob/a7363196a8b1ba730126e8b92dbbd1d45bfdd952/data.py#L50 (lines 50-97). The format is really just a list-of-documents where each document is a list of tokens and a list of class labels. In the example code above you can see how you can use huggingface tokenisers to prepare the list of tokens for each document.
